add display some error, save current file
error: cannot read file, processing error in case transformation type
sbml2math
save current file and data, so that if will uload broken file, user can
continue to work with prev normal file